#!/usr/bin/env bash
set -euo pipefail

PROMPT_TEXT=""
PROMPT_FILE=""
FORCE="0"

usage() {
  cat <<'USAGE'
Usage: ./.ao-tools/prompt-starter.sh [options]

Options:
  --prompt <text>       Prompt text to infer starter shape
  --prompt-file <path>  Read prompt from file
  --force               Recreate starter files if they already exist
  -h, --help            Show help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prompt)
      PROMPT_TEXT="${2:-}"
      shift 2
      ;;
    --prompt-file)
      PROMPT_FILE="${2:-}"
      shift 2
      ;;
    --force)
      FORCE="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[prompt-starter] Unknown arg: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -n "$PROMPT_FILE" ]]; then
  [[ -f "$PROMPT_FILE" ]] || {
    echo "[prompt-starter] prompt file not found: $PROMPT_FILE" >&2
    exit 1
  }
  PROMPT_TEXT="$(cat "$PROMPT_FILE")"
fi

PROMPT_TEXT="$(printf '%s' "$PROMPT_TEXT" | tr -d '\r')"
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

log() {
  printf '[prompt-starter] %s\n' "$*"
}

write_file() {
  local target="$1"
  shift
  if [[ -f "$target" && "$FORCE" != "1" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$target")"
  cat >"$target"
}

if [[ -z "$PROMPT_TEXT" ]]; then
  log "No prompt text supplied. Skip starter scaffolding."
  exit 0
fi

lower="$(printf '%s' "$PROMPT_TEXT" | tr '[:upper:]' '[:lower:]')"
if [[ ! "$lower" =~ fullstack|web\ app|todo|auth|dashboard|api ]]; then
  log "Prompt did not match starter heuristics. Skip scaffolding."
  exit 0
fi

if [[ -d backend && -d frontend && "$FORCE" != "1" ]]; then
  log "backend/ and frontend/ already exist. Skip scaffolding."
  exit 0
fi

mkdir -p backend/src/{api,domain,infra}
mkdir -p frontend/src/{app,features,lib}
mkdir -p tests/{integration,e2e}
mkdir -p docs

write_file backend/README.md <<'EOF'
# Backend Starter

Scaffolded starter structure for AO execution:

- `src/api`: route handlers and transport DTOs
- `src/domain`: business logic and use-cases
- `src/infra`: persistence/integration adapters

Recommended next step: create initial health/auth/todo contract and baseline tests.
EOF

write_file frontend/README.md <<'EOF'
# Frontend Starter

Scaffolded starter structure for AO execution:

- `src/app`: app shell and routing
- `src/features`: feature modules (auth/dashboard/todo)
- `src/lib`: shared api client/state helpers

Recommended next step: define app shell, auth flow, dashboard page, and API wiring.
EOF

write_file tests/README.md <<'EOF'
# Test Starter

- `tests/integration`: backend integration tests
- `tests/e2e`: browser critical-flow tests
EOF

write_file docs/STARTER_NOTES.md <<EOF
# Prompt Starter Notes

Generated by \`.ao-tools/prompt-starter.sh\` to reduce zero-to-one friction.

## Original prompt

\`\`\`
$PROMPT_TEXT
\`\`\`

## Suggested build order

1. Define PRD/HLD/API contract from prompt.
2. Implement backend API/auth/todo domain.
3. Implement frontend auth/dashboard/todo UI.
4. Add integration + e2e coverage for critical flows.
5. Validate release checklist and handover docs.
EOF

write_file .env.example <<'EOF'
PORT=4000
API_BASE_URL=http://localhost:4000
JWT_SECRET=change-me
EOF

log "Starter scaffold created for fullstack workflow."
